# Site settings
title: 蜗牛的博客
owner: 狂奔的蜗牛
email: emsuits@qq.com
description: 在我看来，编程不仅仅是我与生俱来的使命，也是我快乐的源泉。在业余时间，我喜欢研究一些跟技术相关的东西。乐观，善于沟通爱技术，更爱生活和艺术。
baseurl: ""
url: "http://www.emsuits.com"
github: "https://github.com/emsuits"
paginate: 7
#static images
local_url: "/assets/images"
#upyun source
static_url: "http://o79whk727.bkt.clouddn.com"
# Build settings
kramdown:
    input: GFM
permalink: pretty
highlighter: pygments
gems: [jekyll-paginate]
exclude: [node_modules, .tmp, Gruntfile.js, _config, package.json, articles.raw]

# 输出
permalink:     "/:year-:month-:day-:title.html"
paginate_path: "/page/:num"

# default Front matter
defaults:
  -
    scope:
      path: pages
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      copyright: true
      duoshuo_comment: true
      release: true

