# Site settings
title: 芒果小镇
owner: 刘伟家
email: emsuits@qq.com
description: >
  在我看来，编程不仅仅是我与生俱来的使命，也是我快乐的源泉。在业余时间，我喜欢研究一些跟技术相关的东西。同时，我也喜欢做一些安静的事，比如看书、看电影、听音乐、一个人散步以及旅行。
baseurl: ""
url: "http://www.emsuits.com"
#static images
local_url: "/assets/images"
#github source
#static_url: "/assets/images"
#upyun source
static_url: "http://jerryblog-image.b0.upaiyun.com/blog"
#qiniu source
qiniu_static_url: "http://jerryblog.qiniudn.com"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 7
exclude: [node_modules, .tmp, Gruntfile.js, _config, package.json, articles.raw]

# 输出
permalink:     "/:year-:month-:day-:title"
paginate_path: "/page/:num"

# default Front matter
defaults:
  -
    scope:
      path: pages
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      copyright: true
      duoshuo_comment: true
      release: true
